default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root@123

development:
  <<: *default
  database: learn_api_development

test:
  <<: *default
  database: learn_api_test

production:
  <<: *default
  database: learn_api_production
  username: learn_api
  password: <%= ENV["LEARN_API_DATABASE_PASSWORD"] %>
